services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mySecretPass
      POSTGRES_USER: mySecretUser
      POSTGRES_DB: bookedDB
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {} # Added empty braces for clarity
